// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg3gc5Ugm4F1fRhtIKVrIurRB1QVCvKmE',
    appId: '1:45647736838:web:6fcdaa65fe64561eaf5387',
    messagingSenderId: '45647736838',
    projectId: 'myweather-d1bc1',
    authDomain: 'myweather-d1bc1.firebaseapp.com',
    storageBucket: 'myweather-d1bc1.firebasestorage.app',
    measurementId: 'G-40YGCY8VSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxDxRnkkiBns09z26jpIwOg6AkOiFv674',
    appId: '1:45647736838:android:b2dc52f07e9a8782af5387',
    messagingSenderId: '45647736838',
    projectId: 'myweather-d1bc1',
    storageBucket: 'myweather-d1bc1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg3gc5Ugm4F1fRhtIKVrIurRB1QVCvKmE',
    appId: '1:45647736838:web:b8b706353176f3e5af5387',
    messagingSenderId: '45647736838',
    projectId: 'myweather-d1bc1',
    authDomain: 'myweather-d1bc1.firebaseapp.com',
    storageBucket: 'myweather-d1bc1.firebasestorage.app',
    measurementId: 'G-PBP5CYC12K',
  );
}
